config/routes.rb
Rails.application.routes.draw do
  resources :bubbles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "bubbles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bubble.rb
class Bubble < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/bubbles_controller.rb
class BubblesController < ApplicationController
  before_action :set_bubble, only: %i[ show edit update destroy ]

  # GET /bubbles or /bubbles.json
  def index
    @bubbles = Bubble.all
  end

  # GET /bubbles/1 or /bubbles/1.json
  def show
  end

  # GET /bubbles/new
  def new
    @bubble = Bubble.new
  end

  # GET /bubbles/1/edit
  def edit
  end

  # POST /bubbles or /bubbles.json
  def create
    @bubble = Bubble.new(bubble_params)

    respond_to do |format|
      if @bubble.save
        format.html { redirect_to bubble_url(@bubble), notice: "Bubble was successfully created." }
        format.json { render :show, status: :created, location: @bubble }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bubble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bubbles/1 or /bubbles/1.json
  def update
    respond_to do |format|
      if @bubble.update(bubble_params)
        format.html { redirect_to bubble_url(@bubble), notice: "Bubble was successfully updated." }
        format.json { render :show, status: :ok, location: @bubble }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bubble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bubbles/1 or /bubbles/1.json
  def destroy
    @bubble.destroy

    respond_to do |format|
      format.html { redirect_to bubbles_url, notice: "Bubble was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bubble
      @bubble = Bubble.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bubble_params
      params.fetch(:bubble, {})
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ActionController::Base
    def index()
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bubbles_helper.rb
module BubblesHelper
end

app/views/bubbles/_bubble.html.erb
<div id="<%= dom_id bubble %>">
</div>

app/views/bubbles/_form.html.erb
<%= form_with(model: bubble) do |form| %>
  <% if bubble.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bubble.errors.count, "error") %> prohibited this bubble from being saved:</h2>

      <ul>
        <% bubble.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bubbles/edit.html.erb
<h1>Editing bubble</h1>

<%= render "form", bubble: @bubble %>

<br>

<div>
  <%= link_to "Show this bubble", @bubble %> |
  <%= link_to "Back to bubbles", bubbles_path %>
</div>

app/views/bubbles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bubbles</h1>

<div id="bubbles">
  <% @bubbles.each do |bubble| %>
    <%= render bubble %>
    <p>
      <%= link_to "Show this bubble", bubble %>
    </p>
  <% end %>
</div>

<%= link_to "New bubble", new_bubble_path %>

app/views/bubbles/new.html.erb
<h1>New bubble</h1>

<%= render "form", bubble: @bubble %>

<br>

<div>
  <%= link_to "Back to bubbles", bubbles_path %>
</div>

app/views/bubbles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bubble %>

<div>
  <%= link_to "Edit this bubble", edit_bubble_path(@bubble) %> |
  <%= link_to "Back to bubbles", bubbles_path %>

  <%= button_to "Destroy this bubble", @bubble, method: :delete %>
</div>

app/views/layouts/application.html.slim
h1 Hallo!

app/views/layouts/dashboard/index.html.slim
h1 hallo!